@startuml
set namespaceSeparator ::

abstract class "Locato::Background::notification_helper_background.dart::Notifications_helper_background" {
  {static} -FlutterLocalNotificationsPlugin _flutterLocalNotificationsPlugin
  {static} +AndroidInitializationSettings initSettingsAndroid
  {static} +IOSInitializationSettings initSettingsIOS
  {static} +InitializationSettings initSettings
  {static} +AndroidNotificationDetails androidPlatformChannelSpecifics
  {static} +IOSNotificationDetails iOSChannelSpecifics
  {static} +NotificationDetails platformChannelSpecifics
  +FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin
  {static} +dynamic init()
  {static} -Future _onSelectNotification()
  {static} +Future add()
  {static} +Future now()
  {static} +void ListOfTaskNotifi()
  {static} +void ListOfEventNotifi()
  {static} +Future deleteTask()
  {static} +Future deleteEvent()
  {static} +Future deleteNotifi()
  {static} +Future deleteListNotifi()
}

"Locato::Background::notification_helper_background.dart::Notifications_helper_background" o-- "flutter_local_notifications::src::flutter_local_notifications_plugin.dart::FlutterLocalNotificationsPlugin"
"Locato::Background::notification_helper_background.dart::Notifications_helper_background" o-- "flutter_local_notifications::src::platform_specifics::android::initialization_settings.dart::AndroidInitializationSettings"
"Locato::Background::notification_helper_background.dart::Notifications_helper_background" o-- "flutter_local_notifications::src::platform_specifics::ios::initialization_settings.dart::IOSInitializationSettings"
"Locato::Background::notification_helper_background.dart::Notifications_helper_background" o-- "flutter_local_notifications::src::initialization_settings.dart::InitializationSettings"
"Locato::Background::notification_helper_background.dart::Notifications_helper_background" o-- "flutter_local_notifications::src::platform_specifics::android::notification_details.dart::AndroidNotificationDetails"
"Locato::Background::notification_helper_background.dart::Notifications_helper_background" o-- "flutter_local_notifications::src::platform_specifics::ios::notification_details.dart::IOSNotificationDetails"
"Locato::Background::notification_helper_background.dart::Notifications_helper_background" o-- "flutter_local_notifications::src::notification_details.dart::NotificationDetails"

class "Locato::Classes.dart::Event" {
  +int id
  +String name
  +DateTime beginTime
  +DateTime endTime
  +String cycle
  +String color
  +String description
  +List<Notifi> listNotifi
}

class "Locato::Classes.dart::Group" {
  +int id
  +String name
  +int howMuchDone
  +bool isSelected
}

class "Locato::Classes.dart::Localization" {
  +int id
  +double latitude
  +double longitude
  +String name
  +String city
  +String street
  +bool isNearBy
  +bool wasNotified
  +bool isSelected
}

class "Locato::Classes.dart::Notifi" {
  +int id
  +int idTask
  +int idEvent
  +Duration duration
}

class "Locato::Classes.dart::Task" {
  +int id
  +String name
  +bool done
  +DateTime endTime
  +String description
  +Localization localization
  +Group group
  +List<Notifi> listNotifi
}

"Locato::Classes.dart::Task" o-- "Locato::Classes.dart::Localization"
"Locato::Classes.dart::Task" o-- "Locato::Classes.dart::Group"

class "Locato::database_helper.dart::DatabaseHelper" {
  {static} -String _databaseName
  {static} -int _databaseVersion
  {static} +int index
  {static} +DatabaseHelper instance
  {static} -Database _database
  +Future<Database> database
  -dynamic _initDatabase()
  -Future _onCreate()
  +Future insert()
  +Future queryAllRows()
  +Future queryIdRowsTask()
  +Future queryEventWeekend()
  +Future queryEventDay()
  +Future queryTaskNotifiId()
  +Future showalltables()
  +Future query()
  +Future update()
  +Future delete()
}

"Locato::database_helper.dart::DatabaseHelper" o-- "Locato::database_helper.dart::DatabaseHelper"
"Locato::database_helper.dart::DatabaseHelper" o-- "sqflite_common::sqlite_api.dart::Database"

class "Locato::database_helper.dart::EventHelper" {
  {static} +DatabaseHelper dbHelper
  {static} +Future add()
  {static} +Future update()
  {static} +Future delete()
  {static} +Future lists()
  {static} +Future listsDay()
}

"Locato::database_helper.dart::EventHelper" o-- "Locato::database_helper.dart::DatabaseHelper"

class "Locato::database_helper.dart::GroupHelper" {
  {static} +DatabaseHelper dbHelper
  {static} +Future add()
  {static} +Future addlist()
  {static} +Future update()
  {static} +Future delete()
  {static} +Future deleteAndReplaceIdTask()
  {static} +Future getPercent()
  {static} +Future lists()
}

"Locato::database_helper.dart::GroupHelper" o-- "Locato::database_helper.dart::DatabaseHelper"

class "Locato::database_helper.dart::LocalizationHelper" {
  {static} +DatabaseHelper dbHelper
  {static} +Future add()
  {static} +Future addlist()
  {static} +Future updateStatus()
  {static} +Future update()
  {static} +Future delete()
  {static} +Future deleteAndReplaceIdTask()
  {static} +Future lists()
  {static} +Future resetAllStatus()
}

"Locato::database_helper.dart::LocalizationHelper" o-- "Locato::database_helper.dart::DatabaseHelper"

class "Locato::database_helper.dart::NotifiHelper" {
  {static} +DatabaseHelper dbHelper
  {static} +Future add()
  {static} +Future addListNotifiTask()
  {static} +Future addListNotifiEvent()
  {static} +Future update()
  {static} +Future delete()
  {static} +Future deleteTask()
  {static} +Future deleteTaskID()
  {static} +Future deleteEventID()
  {static} +Future lists()
  {static} +Future listsTaskID()
  {static} +Future listsEventID()
  {static} -Duration _parseDuration()
}

"Locato::database_helper.dart::NotifiHelper" o-- "Locato::database_helper.dart::DatabaseHelper"

class "Locato::database_helper.dart::TaskHelper" {
  {static} +DatabaseHelper dbHelper
  {static} +Future add()
  {static} +Future updateDone()
  {static} +Future update()
  {static} +Future delete()
  {static} +Future deleteDoneTaskToday()
  {static} +Future lists()
  {static} +Future listsID()
  {static} +Future listsIDLocal()
}

"Locato::database_helper.dart::TaskHelper" o-- "Locato::database_helper.dart::DatabaseHelper"

class "Locato::main.dart::MyApp" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "Locato::main.dart::MyApp"

class "Locato::main.dart::HomePage" {
  +_HomePageState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "Locato::main.dart::HomePage"

class "Locato::main.dart::_HomePageState" {
  -TabController _tabController
  -PageController _pageController
  +bool pageCanChange
  +void initState()
  +Widget build()
  +dynamic onPageChange()
}

"Locato::main.dart::_HomePageState" o-- "flutter::src::material::tab_controller.dart::TabController"
"Locato::main.dart::_HomePageState" o-- "flutter::src::widgets::page_view.dart::PageController"
"flutter::src::widgets::framework.dart::State<T>" <|-- "Locato::main.dart::_HomePageState"
"flutter::src::widgets::ticker_provider.dart::SingleTickerProviderStateMixin<T>" <|-- "Locato::main.dart::_HomePageState"

class "Locato::Pages::Add_Update_pages.dart::AddEvent" {
  +State<StatefulWidget> addEventState
  +AddEventState createState()
}

"Locato::Pages::Add_Update_pages.dart::AddEvent" o-- "flutter::src::widgets::framework.dart::State<StatefulWidget>"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "Locato::Pages::Add_Update_pages.dart::AddEvent"

class "Locato::Pages::Add_Update_pages.dart::AddEventState" {
  -TextEditingController _controllerName
  -TextEditingController _controllerDesc
  -GlobalKey<FormState> _formKey
  -DateTime _today
  -DateTime _date
  -DateTime _time1
  -DateTime _time2
  -Color _dateColor
  -Color _time1Color
  -Color _time2Color
  -Event _event
  +bool isDateSelected
  +bool isTime1Selected
  +bool isTime2Selected
  +void initState()
  +Widget build()
  +Widget buildCustomTextFieldwithValidation()
  +Widget buildCustomTextField()
  +Widget buildSpace()
  +Widget buildCustomButtonWithValidation()
  +Widget buildCustomButton()
  +Widget buildButtonBar()
  +Widget buildButtonBarTile()
  +Widget buildClearButton()
  +void clearDate()
  +void clearTime1()
  +void clearTime2()
  +void clearNotifiList()
  +void datePick()
  +void startTimePick()
  +void endTimePick()
  +void goBack()
  +void goToNotificationPickPage()
  +void acceptAndValidate()
}

"Locato::Pages::Add_Update_pages.dart::AddEventState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"Locato::Pages::Add_Update_pages.dart::AddEventState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"Locato::Pages::Add_Update_pages.dart::AddEventState" o-- "dart::ui::Color"
"Locato::Pages::Add_Update_pages.dart::AddEventState" o-- "Locato::Classes.dart::Event"
"flutter::src::widgets::framework.dart::State<T>" <|-- "Locato::Pages::Add_Update_pages.dart::AddEventState"

class "Locato::Pages::Add_Update_pages.dart::AddGroup" {
  +Task task
  +List<Group> listOfGroup
  +State<StatefulWidget> stateOfParent
  +_AddGroupState createState()
}

"Locato::Pages::Add_Update_pages.dart::AddGroup" o-- "Locato::Classes.dart::Task"
"Locato::Pages::Add_Update_pages.dart::AddGroup" o-- "flutter::src::widgets::framework.dart::State<StatefulWidget>"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "Locato::Pages::Add_Update_pages.dart::AddGroup"

class "Locato::Pages::Add_Update_pages.dart::_AddGroupState" {
  -GlobalKey<FormState> _formKey
  -TextEditingController _text
  +List<Group> downloadlist
  +List<Group> list
  +void initState()
  -void _downloadData()
  +Widget build()
  +Widget buildListTileWithText()
  +Widget buildCustomTextFieldwithValidation()
  +Widget buildRemoveButton()
  +Widget buildCustomButton()
  +Widget buildSpace()
  +void goBack()
  +void add()
  +void removeFromList()
  +void select()
}

"Locato::Pages::Add_Update_pages.dart::_AddGroupState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"Locato::Pages::Add_Update_pages.dart::_AddGroupState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State<T>" <|-- "Locato::Pages::Add_Update_pages.dart::_AddGroupState"

class "Locato::Pages::Add_Update_pages.dart::AddLocalization" {
  +Task task
  +State<StatefulWidget> stateOfParent
  +State<StatefulWidget> addLocalizationState
  +List<Localization> listOfLocal
  +_AddLocalizationState createState()
}

"Locato::Pages::Add_Update_pages.dart::AddLocalization" o-- "Locato::Classes.dart::Task"
"Locato::Pages::Add_Update_pages.dart::AddLocalization" o-- "flutter::src::widgets::framework.dart::State<StatefulWidget>"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "Locato::Pages::Add_Update_pages.dart::AddLocalization"

class "Locato::Pages::Add_Update_pages.dart::_AddLocalizationState" {
  +List<Localization> localizationlist
  +List<Localization> downloadlist
  +void initState()
  -void _downloadData()
  +Widget build()
  +Widget buildList()
  +Widget buildRemoveButton()
  +Widget buildCustomButton()
  +Widget buildSpace()
  +void goBack()
  +void goToLocationPickPage()
  +void removeFromList()
  +void checkifselected()
}

"flutter::src::widgets::framework.dart::State<T>" <|-- "Locato::Pages::Add_Update_pages.dart::_AddLocalizationState"

class "Locato::Pages::Add_Update_pages.dart::Adres" {
  +String ulica
  +String numerDomu
  +String miasto
  +int odleglosc
  +String toString()
}

class "Locato::Pages::Add_Update_pages.dart::AddLocation" {
  +List<Localization> listofLocal
  +State<StatefulWidget> stateOfParent
  +_AddLocationState createState()
}

"Locato::Pages::Add_Update_pages.dart::AddLocation" o-- "flutter::src::widgets::framework.dart::State<StatefulWidget>"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "Locato::Pages::Add_Update_pages.dart::AddLocation"

class "Locato::Pages::Add_Update_pages.dart::_AddLocationState" {
  +Completer<GoogleMapController> mapController
  +Future<List<Adres>> futureAdresy
  +TextEditingController adresController
  +TextEditingController nazwaController
  +Throttling thrTxt
  {static} -LatLng _initialPosition
  {static} -LatLng _lastPosition
  +Localization dbLokalizacja
  -GlobalKey<FormState> _formKey
  -dynamic _onMapCreated()
  -dynamic _onCameraMove()
  +void initState()
  -InputDecoration _buildInputDecoration()
  -InputDecoration _buildInputDecoration2()
  -void _getLocation()
  +void locationToAddress()
  +Future addressToLocation()
  +Widget build()
  -Widget _buildNazwaLokalizacji()
  -Widget _buildAdres()
  -Widget _buildMapa()
  -Widget _buildDodaj()
}

"Locato::Pages::Add_Update_pages.dart::_AddLocationState" o-- "dart::async::Completer<GoogleMapController>"
"Locato::Pages::Add_Update_pages.dart::_AddLocationState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"Locato::Pages::Add_Update_pages.dart::_AddLocationState" o-- "throttling::src::throttle.dart::Throttling"
"Locato::Pages::Add_Update_pages.dart::_AddLocationState" o-- "google_maps_flutter_platform_interface::src::types::location.dart::LatLng"
"Locato::Pages::Add_Update_pages.dart::_AddLocationState" o-- "Locato::Classes.dart::Localization"
"Locato::Pages::Add_Update_pages.dart::_AddLocationState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"flutter::src::widgets::framework.dart::State<T>" <|-- "Locato::Pages::Add_Update_pages.dart::_AddLocationState"

class "Locato::Pages::Add_Update_pages.dart::AddNotificationTask" {
  +Task task
  +State<StatefulWidget> stateOfParent
  +_AddNotificationTaskState createState()
}

"Locato::Pages::Add_Update_pages.dart::AddNotificationTask" o-- "Locato::Classes.dart::Task"
"Locato::Pages::Add_Update_pages.dart::AddNotificationTask" o-- "flutter::src::widgets::framework.dart::State<StatefulWidget>"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "Locato::Pages::Add_Update_pages.dart::AddNotificationTask"

class "Locato::Pages::Add_Update_pages.dart::_AddNotificationTaskState" {
  -TextEditingController _text
  -GlobalKey<FormState> _formKey
  -List<Notifi> _notifilist
  +dynamic duration
  +int minuty
  +int godziny
  +int dni
  +String name
  +void initState()
  +Widget build()
  +Widget buildPickerNameTile()
  +Widget buildNumberPicker1()
  +Widget buildNumberPicker2()
  +Widget buildNumberPicker3()
  +Widget buildCustomButton()
  +Widget buildSpace()
  +Widget buildCustomTextFieldwithValidation()
  +void validateAndAdd()
  +void goBack()
  +void confirm()
}

"Locato::Pages::Add_Update_pages.dart::_AddNotificationTaskState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"Locato::Pages::Add_Update_pages.dart::_AddNotificationTaskState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"flutter::src::widgets::framework.dart::State<T>" <|-- "Locato::Pages::Add_Update_pages.dart::_AddNotificationTaskState"

class "Locato::Pages::Add_Update_pages.dart::AddNotificationEvent" {
  +Event event
  +State<StatefulWidget> stateOfParent
  +_AddNotificationEventState createState()
}

"Locato::Pages::Add_Update_pages.dart::AddNotificationEvent" o-- "Locato::Classes.dart::Event"
"Locato::Pages::Add_Update_pages.dart::AddNotificationEvent" o-- "flutter::src::widgets::framework.dart::State<StatefulWidget>"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "Locato::Pages::Add_Update_pages.dart::AddNotificationEvent"

class "Locato::Pages::Add_Update_pages.dart::_AddNotificationEventState" {
  -TextEditingController _text
  -GlobalKey<FormState> _formKey
  -List<Notifi> _notifilist
  +dynamic duration
  +int minuty
  +int godziny
  +int dni
  +String name
  +void initState()
  +Widget build()
  +Widget buildPickerNameTile()
  +Widget buildNumberPicker1()
  +Widget buildNumberPicker2()
  +Widget buildNumberPicker3()
  +Widget buildCustomButton()
  +Widget buildSpace()
  +Widget buildCustomTextFieldwithValidation()
  +void validateAndAdd()
  +void goBack()
  +void confirm()
}

"Locato::Pages::Add_Update_pages.dart::_AddNotificationEventState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"Locato::Pages::Add_Update_pages.dart::_AddNotificationEventState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"flutter::src::widgets::framework.dart::State<T>" <|-- "Locato::Pages::Add_Update_pages.dart::_AddNotificationEventState"

class "Locato::Pages::Add_Update_pages.dart::AddTask" {
  +_AddTaskState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "Locato::Pages::Add_Update_pages.dart::AddTask"

class "Locato::Pages::Add_Update_pages.dart::_AddTaskState" {
  -GlobalKey<FormState> _formKey
  -TextEditingController _controllerName
  +TextEditingController controllerDesc
  +Color dateColor
  +Color timeColor
  +bool isNotificationEnabled
  +bool isTimeSelected
  +bool isDateSelected
  +bool isLocalizationSelected
  -DateTime _terminData
  -DateTime _terminCzas
  -DateTime _today
  -Task _task
  +List<Localization> listOfLocalization
  +List<Group> listOfGroup
  +void initState()
  +Widget build()
  +Widget buildButtonBar()
  +Widget buildCustomTextFieldwithValidation()
  +Widget buildClearButton()
  +Widget buildNotifiListClearButton()
  +Widget buildCustomTextField()
  +Widget buildSpace()
  +Widget buildCustomButtonWithValidation()
  +Widget buildCustomButton()
  +Widget buildCustomNotificationButton()
  +Widget buildButtonBarTile()
  +void clearDate()
  +void clearTime()
  +void clearLocalization()
  +void clearGroup()
  +void clearNotifiList()
  +void datePick()
  +void timePick()
  +void goBack()
  +void goToNotificationPickPage()
  +void goToLocalizationPickPage()
  +void goToGroupPickPage()
  +void acceptAndValidate()
}

"Locato::Pages::Add_Update_pages.dart::_AddTaskState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"Locato::Pages::Add_Update_pages.dart::_AddTaskState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"Locato::Pages::Add_Update_pages.dart::_AddTaskState" o-- "dart::ui::Color"
"Locato::Pages::Add_Update_pages.dart::_AddTaskState" o-- "Locato::Classes.dart::Task"
"flutter::src::widgets::framework.dart::State<T>" <|-- "Locato::Pages::Add_Update_pages.dart::_AddTaskState"

class "Locato::Pages::Add_Update_pages.dart::ListNotifi" {
  +List<Notifi> lista
  +_ListNotifiState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "Locato::Pages::Add_Update_pages.dart::ListNotifi"

class "Locato::Pages::Add_Update_pages.dart::_ListNotifiState" {
  +void initState()
  +Widget build()
  +Widget buildSpace()
  +Widget buildSpaceBetween()
  +Widget buildListTextTile()
  +Widget buildRemoveButton()
  +Widget buildListIconTile()
  +void removeFromList()
}

"flutter::src::widgets::framework.dart::State<T>" <|-- "Locato::Pages::Add_Update_pages.dart::_ListNotifiState"

class "Locato::Pages::Add_Update_pages.dart::UpdateEvent" {
  +Event event
  +State<StatefulWidget> updateEventState
  +_UpdateEventState createState()
}

"Locato::Pages::Add_Update_pages.dart::UpdateEvent" o-- "Locato::Classes.dart::Event"
"Locato::Pages::Add_Update_pages.dart::UpdateEvent" o-- "flutter::src::widgets::framework.dart::State<StatefulWidget>"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "Locato::Pages::Add_Update_pages.dart::UpdateEvent"

class "Locato::Pages::Add_Update_pages.dart::_UpdateEventState" {
  -TextEditingController _controllerName
  -TextEditingController _controllerDesc
  -String _name
  -String _description
  -String _date
  -String _time1
  -String _time2
  -String _notification
  -DateTime _start
  -DateTime _end
  -Color _dateColor
  -Color _time1Color
  -Color _time2Color
  +void initState()
  -void _downloadData()
  +Widget build()
  +Widget buildCustomTextFieldwithValidation()
  +Widget buildCustomTextField()
  +Widget buildSpace()
  +Widget buildCustomButtonWithValidation()
  +Widget buildCustomButton()
  +Widget buildButtonBarTile()
  +void datePick()
  +void startTimePick()
  +void endTimePick()
  +void goBack()
  +void goToNotificationPickPage()
  +void acceptAndValidate()
}

"Locato::Pages::Add_Update_pages.dart::_UpdateEventState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"Locato::Pages::Add_Update_pages.dart::_UpdateEventState" o-- "dart::ui::Color"
"flutter::src::widgets::framework.dart::State<T>" <|-- "Locato::Pages::Add_Update_pages.dart::_UpdateEventState"

class "Locato::Pages::Add_Update_pages.dart::UpdateTask" {
  +State<StatefulWidget> updateTaskState
  +Task task
  +_UpdateTaskState createState()
}

"Locato::Pages::Add_Update_pages.dart::UpdateTask" o-- "flutter::src::widgets::framework.dart::State<StatefulWidget>"
"Locato::Pages::Add_Update_pages.dart::UpdateTask" o-- "Locato::Classes.dart::Task"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "Locato::Pages::Add_Update_pages.dart::UpdateTask"

class "Locato::Pages::Add_Update_pages.dart::_UpdateTaskState" {
  -GlobalKey<FormState> _formKey
  -TextEditingController _controllerName
  +TextEditingController controllerDesc
  +int id
  +Color dateColor
  +Color timeColor
  +bool isNotificationEnabled
  +bool isTimeSelected
  +bool isDateSelected
  +bool isLocalizationSelected
  -DateTime _terminData
  -DateTime _terminCzas
  +List<Localization> listOfLocalization
  +List<Group> listOfGroup
  +void initState()
  -void _downloadData()
  +Widget build()
  +Widget buildCustomTextFieldwithValidation()
  +Widget buildClearButton()
  +Widget buildNotifiListClearButton()
  +Widget buildCustomTextField()
  +Widget buildSpace()
  +Widget buildCustomButtonWithValidation()
  +Widget buildCustomButton()
  +Widget buildCustomNotificationButton()
  +Widget buildButtonBarTile()
  +void clearDate()
  +void clearTime()
  +void clearLocalization()
  +void clearGroup()
  +void clearNotifiList()
  +void datePick()
  +void timePick()
  +void goBack()
  +void goToNotificationPickPage()
  +void goToLocalizationPickPage()
  +void goToGroupPickPage()
  +void acceptAndValidate()
  +void onBackPressed()
  +void selectedGroup()
}

"Locato::Pages::Add_Update_pages.dart::_UpdateTaskState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"Locato::Pages::Add_Update_pages.dart::_UpdateTaskState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"Locato::Pages::Add_Update_pages.dart::_UpdateTaskState" o-- "dart::ui::Color"
"flutter::src::widgets::framework.dart::State<T>" <|-- "Locato::Pages::Add_Update_pages.dart::_UpdateTaskState"

class "Locato::Pages::Calendar.dart::Calendar" {
  +_CalendarState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "Locato::Pages::Calendar.dart::Calendar"

class "Locato::Pages::Calendar.dart::_CalendarState" {
  -List _selectedEvents
  -Map<DateTime, List<Event>> _events
  -List<Event> _downloadEvents
  -CalendarController _calendarController
  -DateTime _selectedDay
  +void initState()
  +void dispose()
  -void _onDaySelected()
  +Widget build()
  -Widget _buildTableCalendar()
  -Widget _buildEventsMarker()
  -Widget _buildEventList()
}

"Locato::Pages::Calendar.dart::_CalendarState" o-- "table_calendar::table_calendar.dart::CalendarController"
"flutter::src::widgets::framework.dart::State<T>" <|-- "Locato::Pages::Calendar.dart::_CalendarState"

class "Locato::Pages::GroupPage.dart::GroupCard" {
  +Group group
  +_GroupCardState createState()
}

"Locato::Pages::GroupPage.dart::GroupCard" o-- "Locato::Classes.dart::Group"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "Locato::Pages::GroupPage.dart::GroupCard"

class "Locato::Pages::GroupPage.dart::_GroupCardState" {
  -List<Task> _list
  +int doneTasks
  +void initState()
  +Widget build()
  -Widget _buildContent()
}

"flutter::src::widgets::framework.dart::State<T>" <|-- "Locato::Pages::GroupPage.dart::_GroupCardState"

class "Locato::Pages::GroupPage.dart::GroupCardHeader" {
  +double procent
  +Group group
  +int length
  +int howMuchDone
  +Widget build()
}

"Locato::Pages::GroupPage.dart::GroupCardHeader" o-- "Locato::Classes.dart::Group"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "Locato::Pages::GroupPage.dart::GroupCardHeader"

class "Locato::Pages::GroupPage.dart::GroupCardItem" {
  +Function onPressedDone
  +Function onPressedEdit
  +Function onPressedDelete
  +String name
  +bool done
  +Localization localization
  +String date
  +String description
  +Widget build()
}

"Locato::Pages::GroupPage.dart::GroupCardItem" o-- "Locato::Classes.dart::Localization"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "Locato::Pages::GroupPage.dart::GroupCardItem"

class "Locato::Pages::GroupPage.dart::GroupCardTasks" {
  +List<Task> tasks
  +_GroupCardTasksState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "Locato::Pages::GroupPage.dart::GroupCardTasks"

class "Locato::Pages::GroupPage.dart::_GroupCardTasksState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State<T>" <|-- "Locato::Pages::GroupPage.dart::_GroupCardTasksState"

class "Locato::Pages::GroupPage.dart::GroupTaskPage" {
  +_GroupTaskPageState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "Locato::Pages::GroupPage.dart::GroupTaskPage"

class "Locato::Pages::GroupPage.dart::_GroupTaskPageState" {
  +List<Group> listOfGroup
  +void initState()
  -void _downloadData()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State<T>" <|-- "Locato::Pages::GroupPage.dart::_GroupTaskPageState"

class "Locato::Pages::HomePage.dart::HomePageEvents" {
  +_HomePageEventsState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "Locato::Pages::HomePage.dart::HomePageEvents"

class "Locato::Pages::HomePage.dart::_HomePageEventsState" {
  {static} +List<String> listOfDays
  +int day
  +List<Event> list
  +double heightExtededAppBar
  +double heightImportantEvent
  +double widthImportantEvent
  -DateTime _date
  +void initState()
  +String getDay()
  +Widget build()
  +dynamic refresh()
}

"flutter::src::widgets::framework.dart::State<T>" <|-- "Locato::Pages::HomePage.dart::_HomePageEventsState"

class "Locato::Pages::HomePage.dart::EventCard" {
  +String day
  +List<Event> events
  +Widget build()
  -Widget _buildContent()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "Locato::Pages::HomePage.dart::EventCard"

class "Locato::Pages::HomePage.dart::EventCardEvents" {
  +List<Event> events
  +_EventCardEventsState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "Locato::Pages::HomePage.dart::EventCardEvents"

class "Locato::Pages::HomePage.dart::_EventCardEventsState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State<T>" <|-- "Locato::Pages::HomePage.dart::_EventCardEventsState"

class "Locato::Pages::HomePage.dart::EventCardHeader" {
  +String day
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "Locato::Pages::HomePage.dart::EventCardHeader"

class "Locato::Pages::HomePage.dart::EventCardItem" {
  +String name
  +String eventStart
  +String eventEnd
  +String cycle
  +bool is_cyclic
  +String description
  +Color color
  +Function onPressedEdit
  +Function onPressedDelete
  +_EventCardItemState createState()
}

"Locato::Pages::HomePage.dart::EventCardItem" o-- "dart::ui::Color"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "Locato::Pages::HomePage.dart::EventCardItem"

class "Locato::Pages::HomePage.dart::_EventCardItemState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State<T>" <|-- "Locato::Pages::HomePage.dart::_EventCardItemState"


@enduml